/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "FLY_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}