/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIndexImport } from './routes/auth.index'
import { Route as GithubInstallImport } from './routes/github.install'
import { Route as AuthCallbackImport } from './routes/auth.callback'
import { Route as AppTeamIndexImport } from './routes/_app.$team.index'
import { Route as AppTeamProjectImport } from './routes/_app.$team.$project'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const GithubInstallRoute = GithubInstallImport.update({
  id: '/github/install',
  path: '/github/install',
  getParentRoute: () => rootRoute,
} as any)

const AuthCallbackRoute = AuthCallbackImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRoute,
} as any)

const AppTeamIndexRoute = AppTeamIndexImport.update({
  id: '/$team/',
  path: '/$team/',
  getParentRoute: () => AppRoute,
} as any)

const AppTeamProjectRoute = AppTeamProjectImport.update({
  id: '/$team/$project',
  path: '/$team/$project',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/github/install': {
      id: '/github/install'
      path: '/github/install'
      fullPath: '/github/install'
      preLoaderRoute: typeof GithubInstallImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/$team/$project': {
      id: '/_app/$team/$project'
      path: '/$team/$project'
      fullPath: '/$team/$project'
      preLoaderRoute: typeof AppTeamProjectImport
      parentRoute: typeof AppImport
    }
    '/_app/$team/': {
      id: '/_app/$team/'
      path: '/$team'
      fullPath: '/$team'
      preLoaderRoute: typeof AppTeamIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppTeamProjectRoute: typeof AppTeamProjectRoute
  AppTeamIndexRoute: typeof AppTeamIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppTeamProjectRoute: AppTeamProjectRoute,
  AppTeamIndexRoute: AppTeamIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/github/install': typeof GithubInstallRoute
  '/auth': typeof AuthIndexRoute
  '/$team/$project': typeof AppTeamProjectRoute
  '/$team': typeof AppTeamIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/github/install': typeof GithubInstallRoute
  '/auth': typeof AuthIndexRoute
  '/$team/$project': typeof AppTeamProjectRoute
  '/$team': typeof AppTeamIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/github/install': typeof GithubInstallRoute
  '/auth/': typeof AuthIndexRoute
  '/_app/$team/$project': typeof AppTeamProjectRoute
  '/_app/$team/': typeof AppTeamIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/auth/callback'
    | '/github/install'
    | '/auth'
    | '/$team/$project'
    | '/$team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/auth/callback'
    | '/github/install'
    | '/auth'
    | '/$team/$project'
    | '/$team'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth/callback'
    | '/github/install'
    | '/auth/'
    | '/_app/$team/$project'
    | '/_app/$team/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  GithubInstallRoute: typeof GithubInstallRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  GithubInstallRoute: GithubInstallRoute,
  AuthIndexRoute: AuthIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/auth/callback",
        "/github/install",
        "/auth/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/$team/$project",
        "/_app/$team/"
      ]
    },
    "/auth/callback": {
      "filePath": "auth.callback.tsx"
    },
    "/github/install": {
      "filePath": "github.install.tsx"
    },
    "/auth/": {
      "filePath": "auth.index.tsx"
    },
    "/_app/$team/$project": {
      "filePath": "_app.$team.$project.tsx",
      "parent": "/_app"
    },
    "/_app/$team/": {
      "filePath": "_app.$team.index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
