/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "FLY_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SessionSecret": {
      "type": "random.index/randomPassword.RandomPassword"
      "value": string
    }
    "SessionSecret2": {
      "type": "random.index/randomPassword.RandomPassword"
      "value": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "API": cloudflare.Service
    "Auth": cloudflare.Service
    "AuthKV": cloudflare.KVNamespace
    "SessionSecret": cloudflare.
    "SessionSecret2": cloudflare.
  }
}

import "sst"
export {}